import type { Metadata } from "next";
import localFont from "next/font/local";
import { Inter, Rubik } from "next/font/google";
import "./globals.css";


// Load Google Fonts
const inter = Inter({ 
  subsets: ["latin"], 
  variable: "--font-inter" 
});

const rubik = Rubik({
   subsets: ["latin"], 
   variable: "--font-rubik" 
});

// Load Custom Font (Asgard Trial)
const asgard = localFont({
  src: "../public/fonts/AsgardTrial-WideXbold.ttf", 
  variable: "--font-asgard", 
});

const asgardRegular = localFont({
  src: "../public/fonts/AsgardTrial-WideRegular.ttf", 
  variable: "--font-asgard", 
});

 // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//  className={`${inter.variable} ${rubik.variable} ${asgard} antialiased`}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
       
    
        {children}
      </body>
    </html>
  );
}

